[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "re2py"
version = "0.0.1"
authors = [
  { name="msk-ono", email="aaikmnoos@gmail.com" },
]
description = "Regex matcher"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "graphviz~=0.20"
]

[project.urls]
Homepage = "https://github.com/msk-ono/re2py"
Issues = "https://github.com/msk-ono/re2py/issues"
